### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by AlexHedley** [AlexHedley/PoshLenovo#18]
Fix my awful attempt at an icon

![Icon](https://raw.githubusercontent.com/Protirus/PoshLenovo/dev/icon.png)

**PowerShell**
![PowerShell](https://upload.wikimedia.org/wikipedia/commons/2/2f/PowerShell_5.0_icon.png)
- https://github.com/exercism/meta/issues/81

**Lenovo**
![Lenovo](https://static.lenovo.com/fea/images/lenovo-logo-red.png)

**Comment by Axemasta** [comment]
Addressed in PR #19

**Comment by AlexHedley** [comment]
TODO: Update manifest to point to this new image.

**Comment by AlexHedley** [comment]
7359597693b194ed5e7419f6941dcbe85e9d97ad
